### PR TITLE
Improvements to desktop file, metainfo/appdata & README.md

### PR DESCRIPTION
**Pull request by sungsphinx**
Changed/Fixed grammar in some places, moved the donate section to the top, changed all-caps words, and make the README look a bit better in general.

Fixed the app from showing in the start menu/launcher as 'retrospriteeditor'

Add vcs-browser to metainfo (which basically takes you to the app source code)

Add 'Graphics' and '2DGraphics' categories to the metainfo & desktop file

Add keywords in the metainfo: 
```
  <keywords>
    <keyword>2D</keyword>
    <keyword>2D Graphics</keyword>
    <keyword>Graphics</keyword>
    <keyword>Retro</keyword>
    <keyword>Retro Art</keyword>
    <keyword>Pixel Art</keyword>
    <keyword>NES</keyword>
    <keyword>Console</keyword>
  </keywords>
```

Probably more changes that I haven't listed here, and obviously feel free to change anything to your liking.

### CODE REVIEW

**Comment by xverizex** [comment]
Oh, thanks you.

**Comment by xverizex** [comment]
I understood that I had to wait until you completed the pull draft? Was I in a hurry?

**Comment by sungsphinx** [comment]
I was just going to add a small thing to the README and I could open a new PR anyway if I needed too, but it's ok.

It was something like this (navigation links):

Screenshot from 2024-01-05 18-40-40

**Comment by xverizex** [comment]
Ok. Thanks for help me.

**Pull request merged**
